config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  get '/songs' => 'home#songs'
  get '/contact'=> 'home#contact'

  namespace :admin do
    get '/dashboard' => 'admin#dashboard'
    resources :albums
    resources :artists
    resources :songs
    resources :genres
  end

  namespace :tuner do
    resources :favorites, only: [:index, :create, :destroy]
    resources :playlists
    resources :playlist_songs, only: [:create, :destroy]
    resources :songs, only: [:index, :show]
    get '/index' => 'profile#index'

  end
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
  belongs_to :user

  has_many :songs

  validates :name, presence: true, length: { maximum: 20 }
  validates :year, presence: true, numericality: true
end

app/controllers/admin/albums_controller.rb
class Admin::AlbumsController < Admin::AdminController
	before_action :find_album, { only: [:edit, :update, :show, :destroy] }

	def index
    @albums = Album.all
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
    @album.user_id = current_user.id

    if @album.save
      flash[:notice] = 'Album created successfully!.'
      redirect_to admin_albums_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @album.update(album_params)
      redirect_to admin_albums_path
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @album.destroy
    flash[:notice] = 'Album deleted successfully!'
    redirect_to admin_albums_path
  end

  private

  def album_params
    params.require(:album).permit(:name, :year, :artist_id);
  end

  def find_album
    @album = Album.find(params[:id])
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
	before_action :find_album, { only: [:edit, :update, :show, :destroy] }

	def index
    @albums = Album.all
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
    @album.user_id = current_user.id

    if @album.save
      flash[:notice] = 'Album created successfully!.'
      redirect_to albums_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @album.update(album_params)
      redirect_to albums_path
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @album.destroy
    flash[:notice] = 'Album deleted successfully!'
    redirect_to albums_path
  end

  private

  def album_params
    params.require(:album).permit(:name, :year, :artist_id);
  end

  def find_album
    @album = Album.find(params[:id])
  end
end

app/views/admin/albums/_album.html.erb
<tr>
  <td><%= link_to album.name, admin_album_path(album) %></td>
  <td><%= album.year %></td>
  <td><%= album.artist.name %></td>
  <td>
  <div class="btn-group">
    <% if current_user.superadmin? || current_user.id == album.user_id %>
      <%= link_to 'Edit', edit_admin_album_path(album), class: 'btn btn-sm btn-primary' %>
      <%= link_to 'Delete', admin_album_path(album), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-sm btn-danger' %>
    <% end %>
    </div>
  </td>
</tr>

app/views/admin/albums/_form.html.erb
<%= form_for [:admin, @album] do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name, class: 'form-control' %>
  <%= error_for :name, @album.errors %>
  <br>
  <%= form.label :year, 'Relase year' %>
  <%= form.text_area :year, class: 'form-control' %>
  <%= error_for :year, @album.errors %>
  <br>
  <%= form.label :artist_id %>
  <%= form.collection_select :artist_id, Artist.all, :id, :name, { prompt: 'Choose artist' }, class: 'form-control' %>
  <%= error_for :artist, @album.errors %>
  <br>
  <%= form.submit params[:action] == 'new' ? 'Save' : 'Update', class: 'btn btn-block btn-primary' %>
<% end %>

app/views/admin/albums/edit.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <br>
    <h1>Update album</h1>
    <br>
    <%= render 'shared/validation_messages', model: @album %>
    <%= render 'form' %>
  </div>
</div>

app/views/admin/albums/index.html.erb
<div class="row">
  <div class="col-md-7">
    <h1>Albums <%= link_to 'Create new', new_admin_album_path, class: 'btn btn-success' %></h1>
    <% unless flash[:notice].blank? %>
      <div class="alert alert-success">
        <p><%= flash[:notice] %></p>
      </div>
    <% end %>

    <h3>Album details</h3>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Name</th>
          <th>Year</th>
          <th>Artist</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <%= render @albums %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/albums/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <br>
    <h1>Create album</h1>
    <br>

    <%= render 'shared/validation_messages', model: @album %>
    <%= render 'form' %>
  </div>
</div>

app/views/admin/albums/show.html.erb
<div class="row">
  <div class="col-md-6">
    <p><strong>Name:</strong></p>
    <p><%= @album.name %></p>
    <br>
    <p><strong>Artist:</strong></p>
    <p><%= @song.artist.name %></p>
    <br>
    <p><strong>Year:</strong></p>
    <p><%= @album.year %></p>
    <br>
  </div>
</div>