config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  get '/songs' => 'home#songs'
  get '/contact'=> 'home#contact'

  namespace :admin do
    get '/dashboard' => 'admin#dashboard'
    resources :albums
    resources :artists
    resources :songs
    resources :genres
  end

  namespace :tuner do
    resources :favorites, only: [:index, :create, :destroy]
    resources :playlists
    resources :playlist_songs, only: [:create, :destroy]
    resources :songs, only: [:index, :show]
    get '/index' => 'profile#index'

  end
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album
  belongs_to :genre
  belongs_to :user

  has_many :playlist_songs

  validates :name, presence: true, length: { maximum: 20 }
	validates :duration, presence: true, length: { maximum: 10 }
  validates :youtubelink, presence: true, length: { maximum: 50 }
end

app/controllers/admin/songs_controller.rb
class Admin::SongsController < Admin::AdminController
	before_action :find_song, { only: [:edit, :update, :show, :destroy] }

	def index
  	@songs = Song.all
	end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)
		@song.user_id = current_user.id

    if @song.save
      flash[:notice] = 'Song created successfully!'
      redirect_to admin_songs_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @song.update(song_params)
      redirect_to admin_song_path
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @song.destroy
    flash[:notice] = 'Song deleted successfully!!'
    redirect_to admin_songs_path
  end

  private

  def song_params
    params.require(:song).permit(:name, :duration, :album_id, :genre_id, :youtubelink);
  end

  def find_song
    @song = Song.find(params[:id])
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
	before_action :find_song, { only: [:edit, :update, :show, :destroy] }

	def index
  	@songs = Song.all
	end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)

    if @song.save
      flash[:notice] = 'Song created successfully!'
      redirect_to songs_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @song.update(song_params)
      redirect_to song_path
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @song.destroy
    flash[:notice] = 'Song deleted successfully!!'
    redirect_to songs_path
  end

  private

  def song_params
    params.require(:song).permit(:name, :duration, :album_id);
  end

  def find_song
    @song = Song.find(params[:id])
  end
end

app/controllers/tuner/favorites_controller.rb
class Tuner::FavoritesController < Tuner::TunerController
  def index
    @favorites = Favorite.where(user_id: current_user.id)
  end

  def create
    @favorite = Favorite.create(user_id: current_user.id, song_id: params[:song_id])
    redirect_to tuner_songs_path, notice: 'This song is in your favorites now!'
  end

  def destroy
    @favorite = Favorite.where(user_id: current_user.id, song_id: params[:id]).first.destroy
    redirect_to tuner_songs_path, notice: 'Song is no longer in your favorites!'
  end

end

app/controllers/tuner/playlist_songs_controller.rb
class Tuner::PlaylistSongsController < Tuner::TunerController

  def create
    @playlist_song = PlaylistSong.create(playlist_id: params[:playlist_id], song_id: params[:song_id])
    redirect_to tuner_playlist_path(params[:playlist_id]), notice: 'This song is in your playlist!'
  end

  def destroy
    @playlist_song = PlaylistSong.find(params[:id])
    @playlist_song.destroy
    redirect_to tuner_playlist_path(@playlist_song.playlist), notice: 'Song is no longer in your playlist!'
  end
end

app/controllers/tuner/playlists_controller.rb
class Tuner::PlaylistsController < Tuner::TunerController
	before_action :find_playlist, { only: [:edit, :update, :show, :destroy] }

	def index
    @playlists = Playlist.where(user_id: current_user.id)
  end

  def new
    @playlist = Playlist.new
  end

  def create
    @playlist = Playlist.new(playlist_params)
    @playlist.user_id = current_user.id

    if @playlist.save
      flash[:notice] = 'Playlist created successfully.'
      redirect_to tuner_playlists_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @playlist.update(playlist_params)
      redirect_to tuner_playlist_path
    else
      render :edit
    end
  end

  def show
		@playlistsongs = @playlist.playlist_songs
  end

  def destroy
    @playlist.destroy
    flash[:notice] = 'Playlist deleted successfully!'
    redirect_to tuner_playlists_path
  end

  private

  def playlist_params
    params.require(:playlist).permit(:name, :user_id);
  end

  def find_playlist
    @playlist = Playlist.find(params[:id])
  end
end

app/controllers/tuner/profile_controller.rb
class Tuner::ProfileController < Tuner::TunerController

  def index

  end
end

app/controllers/tuner/songs_controller.rb
class Tuner::SongsController < Tuner::TunerController
	before_action :find_song, { only: [:show] }

	def index
		if params[:search].nil?
			@songs = Song.all
		else
  		@songs = Song.where("name like ?", "%"+params[:search]+"%")
		end
	end

  def show
		
  end

  private

  def song_params
    params.require(:song).permit(:name, :duration, :album_id, :genre_id);
  end

  def find_song
    @song = Song.find(params[:id])
  end
end

app/controllers/tuner/tuner_controller.rb
class Tuner::TunerController < ApplicationController
  
end

app/views/tuner/songs/_song.html.erb
<tr>
  <td><%= link_to song.name, tuner_song_path(song) %></td>
  <td><%= song.album.artist.name %></td>
  <td><%= song.album.name %></td>
  <td><%= song.duration %></td>
  <td><%= song.genre.name %></td>
  <td>
    <div class="btn-group">
      <% if Favorite.where(song_id: song.id, user_id: current_user.id).empty? %>
        <%= link_to tuner_favorites_path(song_id: song.id), method: :post, class: '' do %>
          <i class="fa fa-heart-o" aria-hidden="true"></i>
        <% end %>
      <% else %>
        <%= link_to tuner_favorite_path(song.id), method: :delete, class: '' do %>
          <i class="fa fa-heart" aria-hidden="true"></i>
        <% end %>
      <% end %>
    </div>
  </td>
  <td>
    <%= link_to song.youtubelink, class: '', target: "_blank" do %>
      <i class="fa fa-youtube-play" aria-hidden="true"></i>
    <% end %>
  </td>
  <td>
    <%= link_to tuner_playlist_songs_path(song_id: song.id, playlist_id: current_user.playlists.first.id), method: :post do %>
      <i class="fa fa-list-ul" aria-hidden="true"></i>
    <% end %>
  </td>
</tr>

app/views/tuner/songs/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7">

      <% unless flash[:notice].blank? %>
        <div class="alert alert-success">
          <p><%= flash[:notice] %></p>
        </div>
      <% end %>

      <h3>Songs details</h3>

      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Name</th>
            <th>Artist</th>
            <th>Album</th>
            <th>Duration</th>
            <th>Genre</th>
            <th>Make a favorite</th>
            <th>Play the song</th>
            <th>Add to playlist</th>
          </tr>
        </thead>
        <tbody>
          <%= render @songs %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/tuner/songs/show.html.erb
<div class="row">
  <div class="col-md-6">
    <p><strong>Name:</strong></p>
    <p><%= @song.name %></p>
    <br>
    <p><strong>Artist:</strong></p>
    <p><%= @song.album.artist.name %></p>
    <br>
    <p><strong>Album:</strong></p>
    <p><%= @song.album.name %></p>
    <br>
    <p><strong>Duration:</strong></p>
    <p><%= @song.duration %></p>
    <br>
    <p><strong>Genre:</strong></p>
    <p><%= @song.genre.name %></p>
    <br>
  </div>
</div>