config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  get '/songs' => 'home#songs'
  get '/contact'=> 'home#contact'

  namespace :admin do
    get '/dashboard' => 'admin#dashboard'
    resources :albums
    resources :artists
    resources :songs
    resources :genres
  end

  namespace :tuner do
    resources :favorites, only: [:index, :create, :destroy]
    resources :playlists
    resources :playlist_songs, only: [:create, :destroy]
    resources :songs, only: [:index, :show]
    get '/index' => 'profile#index'

  end
end

app/views/shared/_header.html.erb
<div id="header">
  <div class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navMain">
          <span class="glyphicon glyphicon-chevron-left" style="color:white;"></span>
          </button>
      </div>
      <div id="page-content-wrapper">
        <% if user_signed_in? %>
          <a href="#menu-toggle" class="btn btn-default" id="menu-toggle"><i class="fa fa-bars" aria-hidden="true"></i></a>
        <% end %>
        <ul class="nav navbar-nav pull-right">
          <% unless user_signed_in? %>
            <li><%= link_to 'Login', new_user_session_path %></li>
            <li><%= link_to 'Register', new_user_registration_path %></li>
          <% end %>
          <% if user_signed_in? %>
            <li class="dropdown">
              <a data-toggle="dropdown" class="dropdown-toggle" href="#">Logged in as: <%= current_user.email %> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Edit Account', edit_user_registration_path %></li>
                <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
                <% if current_user.admin? || current_user.superadmin? %>
                  <li><%= link_to 'Dashboard', admin_dashboard_path %></li>
                <% end %>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<% if user_signed_in? %>
<div id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <%= image_tag 'icon.jpg', :class => "brand" %>
    <li class="sidebar-header"> My Tunes </li>


      <%= form_tag(tuner_songs_path, method: "get", class: "navbar-form") do %>
        <div class="input-group add-on">
          <%= text_field_tag(:search,"", class: 'form-control') %>
          <div class="input-group-btn">
            <%= button_tag(type: "submit", :class=>"btn btn-default") do %>
              <i class="glyphicon glyphicon-search"></i>
            <% end %>
          </div>
        </div>
      <% end %>
      <% if current_user.admin? || current_user.superadmin? %>
        <div class="lists">
          <li class="<%= 'active' if params[:controller]=='home' && params[:action] == 'index' %>"><%= link_to 'Homepage', root_path %></li>
          <li class="<%= 'active' if params[:controller]=='songs' && params[:action] == 'index' %>"><%= link_to 'Songs', admin_songs_path %></li>
          <li class="<%= 'active' if params[:controller]=='albums' && params[:action] == 'index' %>"><%= link_to 'Albums', admin_albums_path %></li>
          <li class="<%= 'active' if params[:controller]=='artists' && params[:action] == 'index' %>"><%= link_to 'Artists', admin_artists_path %></li>
          <li class="<%= 'active' if params[:controller]=='genres' && params[:action] == 'index' %>"><%= link_to 'Genres', admin_genres_path %></li>
        </div>
      <% else %>
        <div class="lists">
          <li class="<%= 'active' if params[:controller]=='home' && params[:action] == 'index' %>"><%= link_to 'Homepage', root_path %></li>
          <li class="<%= 'active' if params[:controller]=='home' && params[:action] == 'index' %>"><%= link_to 'Songs', tuner_songs_path %></li>
          <li class="<%= 'active' if params[:controller]=='tuner_index' && params[:action] == 'index' %>"><%= link_to 'My profile', tuner_index_path %></li>
          <li class="<%= 'active' if params[:controller]=='home' && params[:action] == 'index' %>"><%= link_to 'My Playlists', tuner_playlists_path %></li>
          <li class="<%= 'active' if params[:controller]=='home' && params[:action] == 'index' %>"><%= link_to 'Favorite tracks', tuner_favorites_path %></li>
          <li class="<%= 'active' if params[:controller]=='home' && params[:action] == 'contact' %>"><%= link_to 'Contact us', contact_path %></li>
        </div>
      <% end %>
    </ul>
</div>
<% end %>

app/views/shared/_validation_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-danger alert-dismissable fade in">
  	<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    	<% model.errors.full_messages.each do |error| %>
      <p><%= error %></p>
    <% end %>
  </div>
<% end %>