config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  get '/songs' => 'home#songs'
  get '/contact'=> 'home#contact'

  namespace :admin do
    get '/dashboard' => 'admin#dashboard'
    resources :albums
    resources :artists
    resources :songs
    resources :genres
  end

  namespace :tuner do
    resources :favorites, only: [:index, :create, :destroy]
    resources :playlists
    resources :playlist_songs, only: [:create, :destroy]
    resources :songs, only: [:index, :show]
    get '/index' => 'profile#index'

  end
end

app/models/genre.rb
class Genre < ApplicationRecord
	belongs_to :user
	has_many :songs
  validates :name, presence: true, length: { maximum: 20 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < Admin::AdminController
	before_action :find_genre, { only: [:edit, :update, :show, :destroy] }

	def index
    @genres = Genre.all
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
		@genre.user_id = current_user.id

    if @genre.save
      flash[:notice] = 'Genre created successfully.'
      redirect_to admin_genres_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @genre.update(genre_params)
      redirect_to admin_genre_path
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @genre.destroy
    flash[:notice] = 'Genre deleted successfully!'
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name);
  end

  def find_genre
    @genre = Genre.find(params[:id])
  end
end

app/views/admin/genres/_form.html.erb
<%= form_for [:admin, @genre] do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name, class: 'form-control' %>
  <%= error_for :name, @genre.errors %>
  <br>
  <%= form.submit params[:action] == 'new' ? 'Save' : 'Update', class: 'btn btn-block btn-primary' %>
<% end %>

app/views/admin/genres/_genre.html.erb
<tr>
  <td><%= link_to genre.name, admin_genre_path(genre) %></td>
  <td>
    <div class="btn-group">
      <% if current_user.superadmin? || current_user.id == genre.user_id %>
        <%= link_to 'Edit', edit_admin_genre_path(genre), class: 'btn btn-sm btn-primary' %>
        <%= link_to 'Delete', admin_genre_path(genre), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-sm btn-danger' %>
      <% end %>
    </div>
  </td>
</tr>

app/views/admin/genres/edit.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <br>
    <h1>Update genre</h1>
    <br>

    <%= render 'shared/validation_messages', model: @genre %>
    <%= render 'form' %>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="row">
  <div class="col-md-7">
    <h1>Genres <%= link_to 'Create new', new_admin_genre_path, class: 'btn btn-success' %></h1>


    <% unless flash[:notice].blank? %>
      <div class="alert alert-success">
        <p><%= flash[:notice] %></p>
      </div>
    <% end %>

    <h3>Genre details</h3>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Name</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <%= render @genres %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/genres/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <br>
    <h1>Create genre</h1>
    <br>

    <%= render 'shared/validation_messages', model: @genre %>
    <%= render 'form' %>
  </div>
</div>

app/views/admin/genres/show.html.erb
<div class="row">
  <div class="col-md-6">
    <p><strong>Name:</strong></p>
    <p><%= @genre.name %></p>
    <br>
  </div>
</div>